[app]
data_db = "data/auto_sync.sqlite"
log_dir = "logs"
status_log_interval_secs = 300
port = 18765
tcp_connection_pool_size = 100

[app.sync]
mirror = true
checksum = false
debug_logs = false
transfer_timeout_secs = 120
bwlimit_kbps = 0
max_parallel_transfers = 32
modify_window_secs = 1

[[machines]]
id = "dev"
name = "dev"
alias_name = "dev"
host = "192.168.2.126"
port = 18765
ssh_user = "root"
ssh_port = 10022
os = "linux"
install_dir = "/opt/auto_sync"
enabled = true
manual = true

[[machines]]
id = "nas"
name = "tiger"
alias_name = "nas"
host = "192.168.2.247"
port = 18765
ssh_user = "root"
ssh_port = 10022
os = "linux"
install_dir = "/opt/auto_sync"
enabled = true
manual = true

[[machines]]
id = "Windows"
name = "DESKTOP-576IPE3"
alias_name = "nWindowsas"
host = "192.168.2.166"
port = 18765
ssh_user = "Administrator"
ssh_port = 22
os = "windows"
install_dir = "C:/auto_sync"
enabled = true
manual = true

[[machines]]
id = "OpenWrt"
name = "OpenWrt"
alias_name = "OpenWrt"
host = "192.168.2.1"
port = 18765
ssh_user = "root"
ssh_port = 10022
os = "linux"
install_dir = "/usr/local/auto_sync"
enabled = true
manual = true
