[app]
data_db = "conf/state/auto_sync.sqlite"
log_dir = "logs"
status_log_interval_secs = 300
web_bind = "0.0.0.0:18765"
tcp_connection_pool_size = 100

[app.sync]
mirror = true
checksum = false
debug_logs = false
transfer_timeout_secs = 120
bwlimit_kbps = 0
max_parallel_transfers = 32
modify_window_secs = 1

[[machines]]
id = "local"
name = "This machine"
host = "192.168.2.166"
web_port = 18765
ssh_user = ""
ssh_port = 22
os = "windows"
enabled = true
manual = true

[[machines]]
id = "nas"
name = "nas"
host = "192.168.2.247"
web_port = 18765
ssh_user = "root"
ssh_port = 10022
os = "linux"
enabled = true
manual = true

[[machines]]
id = "openwrt"
name = "openwrt"
host = "192.168.2.1"
web_port = 18765
ssh_user = "root"
ssh_port = 10022
os = "linux"
enabled = true
manual = true

[[source_groups]]
id = "src_1"
src = '\\?\C:\Users\tiger\Documents\xwechat_files'
enabled = true
mode = "mirror"

[source_groups.snapshot]
backend = "auto"
prefix = "auto_sync"
reconcile_interval_secs = 900
keep_extra_cycles = 2

[[source_groups.destinations]]
id = "dst_1"
machine_id = "nas"
path = "/opt"
enabled = true

[source_groups.destinations.schedule]
mode = "realtime"
time = "02:00"
timezone = "local"
weekday = "monday"
sync_current_cycle_manually = false

[[deploy.targets]]
id = "tiger"
host = "localhost"
port = 22
user = "root"
install_dir = "/usr/local/auto_sync"

[[deploy.targets]]
id = "nas"
host = "192.168.2.247"
port = 10022
user = "root"
install_dir = "/usr/local/auto_sync"

[[deploy.targets]]
id = "windows"
host = "192.168.3.7"
port = 22
user = "Administrator"
install_dir = "C:/auto_sync"

[[deploy.targets]]
id = "openwrt"
host = "192.168.2.1"
port = 10022
user = "root"
install_dir = "/usr/local/auto_sync"
